# Generated by Django 6.0 on 2025-12-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=255)),
                ('fatherName', models.CharField(max_length=255)),
                ('motherName', models.CharField(max_length=255)),
                ('presentAddress', models.TextField()),
                ('permanentAddress', models.TextField()),
                ('dateOfBirth', models.DateField()),
                ('mobile', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('bloodGroup', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=50)),
                ('academicYear', models.CharField(max_length=20)),
                ('classCode', models.CharField(max_length=20)),
                ('sectionCode', models.CharField(max_length=20)),
                ('groupCode', models.CharField(max_length=20)),
            ],
        ),
    ]
